sudo: false
language: ruby

script: bundle exec ruby spec/unicode_blocks_spec.rb

rvm:
- ruby-head
- 2.5.0
- 2.4.1
- 2.3.4
- 2.2
- 2.1
- 2.0
- jruby-head
- jruby-9.1.15.0

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: 2.1
    - rvm: 2.0
